Spotify extension
albertlauncher/plugins pull request #43
Opened 2021-01-27 16:08 UTC by BlueManCZ

I created a Spotify extension for Albert launcher. It allows user to search and play tracks, add them to the queue and choose particular Spotify client.

This code **needs review and testing**. It works without any problems for me, but there may be unpredictable situational problems, that I'm currently not aware of.

For all people willing to use this extension, **please read** [README.md](https://github.com/BlueManCZ/plugins/blob/spotify-plugin/spotify/README.md) **first**. I described there how to configure Spotify Web API in this extension.

It is `QueryHandler::ExecutionType::Realtime` and currently contains `spotify` and `play` triggers.

![Spotify extension](https://camo.githubusercontent.com/d7d4fbd3b766ac2c187ca886acb41aab077b5caf068c7ffa5c5dc68a1fb57e9e/68747470733a2f2f692e696d6775722e636f6d2f436f45324335692e706e67)

2021-07-19 20:40 UTC, Bierchermuesli commented
nice! but do this extension depends on QT 5.15?

```
tmp/albert-source/plugins/spotify/src/extension.cpp:104:65: error: ‘textChanged’ is not a member of ‘QSpinBox’
  104 |     connect(d->widget->ui.spinBox_number_of_results, &QSpinBox::textChanged, [this](const QString &s){

```

```
qmake -v
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa


```

2021-07-20 07:20 UTC, BlueManCZ commented
Hello! To be honest I don't know right now. I'm on vacation and I will take a look when I come back. 😉

2021-07-24 17:57 UTC, BlueManCZ commented
@Bierchermuesli According to the [docs](https://doc.qt.io/qt-5/qspinbox.html#textChanged), `textChanged` was introduced in Qt 5.14. Do you think it's a problem?

2021-07-25 09:13 UTC, Bierchermuesli commented
just a Problem of outdated Qt version in some distros :-) 
 ≤ Debian 10 or ≤ Ubuntu 20.04 (LTS) still have Qt 5.11.3.  

Debian 11 (soon stable) has Qt 5.14 and Ubuntu >20.10 has Qt5.14

2022-06-06 13:48 UTC, BlueManCZ commented
Is there anything I can do to help you merge this @ManuelSchneid3r? Or are you working on some breaking changes in the core that will require adaptation?

I've used this extension for more than one year and didn't notice a single problem.

2022-10-08 11:49 UTC, ManuelSchneid3r commented
> Do you think it's a problem?

currently albert is backward compatible until ubuntu [18.04 i.e. 5.9. 20.04 uses 5.12.](https://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=libqt5gui5)

2022-10-11 16:11 UTC, idkCpp requested changes
I'm very sorry, but this is in bad shape.

2022-10-11 16:11 UTC, idkCpp commented on spotify/src/spotifyWebAPI.h
> +    QString DEVICES_URL = "https://api.spotify.com/v1/me/player/devices";
These all look very const despite none of them are.

2022-10-11 17:27 UTC, ManuelSchneid3r commented on spotify/src/extension.cpp
> +    d->api->manager = new QNetworkAccessManager();
Please use unique_ptr to avoid memory leaks

2022-10-11 17:29 UTC, ManuelSchneid3r commented on spotify/src/extension.cpp
> +    if (!d->api->testInternetConnection()) {
Well it is accessing a web api, hence it's necessary. I agree please use (short) timeouts

2022-10-11 17:30 UTC, ManuelSchneid3r commented on spotify/src/extension.cpp
> +        d->api->downloadImage(track.imageUrl, filename);
Unfortunately yes, but in this case we can't get better than the lag introduces by the requests

2022-12-27 10:33 UTC, ManuelSchneid3r commented
Please port it to 0.18. Looking forward to finally use this one :D

2023-01-24 11:57 UTC, ManuelSchneid3r commented
Will a subset of features work withou a premium account?

2023-03-29 15:44 UTC, ManuelSchneid3r commented
@BlueManCZ do you still want this plugin to be merged?

2023-03-29 16:14 UTC, BlueManCZ commented
Excuse me for not replying sooner.

> I'm very sorry, but this is in bad shape.

Thank you for the code review @idkCpp, I will try to refactor this when porting to the new Albert core. You were right, that ton of managers was indeed a threading problem.

> Please port it to 0.18. Looking forward to finally use this one :D

As soon as I get Qt6 and build working on Gentoo, I will try to port it.

> Will a subset of features work without a premium account?

I'm not sure. I can't imagine what that subset would be. Based on the sentence from [API documentation](https://developer.spotify.com/documentation/web-api/tutorials/getting-started):
_"This tutorial assumes you have a Spotify account (free or premium)."_
maybe some will work. But you can't select a specific song to play without Spotify premium.

> @BlueManCZ do you still want this plugin to be merged?

I do, but I still don't have Qt6 on Gentoo to port this to the new Albert core. But I keep this in mind and watch Telegram for news.

2023-03-29 18:05 UTC, CaseOf commented
@BlueManCZ my ebuild for Qt6 Albert is ready and working. I just have to commit it, and do a pull request on gentoo repository.
It wont be merged quickly as I know them, and the have to review ebuilds for qtscxml and qhotkey too in the same PR.
You can manually add it to a local overlay for testing.

2023-03-29 22:06 UTC, CaseOf commented
Here is my pull request on gentoo repository https://github.com/gentoo/gentoo/pull/30405

2023-03-30 09:17 UTC, ManuelSchneid3r commented
@BlueManCZ ill close this one for now. Please reopen or make a new one if it is time for it.

2023-03-30 09:17 UTC, closed without merging